version: '3'
services:
    backend:
        image: strapi/strapi
        volumes:
            - ./app:/srv/app
        ports:
            - 3001:1337
        restart: unless-stopped
    frontend:
        build: frontend
        volumes:
            - /code/node_modules
            - ./frontend:/code
        ports:
            - 3000:3000
        restart: unless-stopped
