version: '3'
services:
    backend:
        image: strapi/strapi
        volumes:
            - ./app:/srv/app
        ports:
          - 3001:1337
        restart: unless-stopped
    frontend:
        build: 
          context: frontend
          dockerfile: Dockerfile.local
        volumes:
            - /code/node_modules
            - ./frontend:/code
        restart: unless-stopped
    reverse-proxy:
      depends_on:
        - frontend
        - backend
      image: caddy:latest
      ports:
        - 3000:3000
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
      restart: unless-stopped
